export { default as FooterImage } from "./Footer.png";
export { default as NonoImage } from "./nono new 1.png";
export { default as GirlRunningImage } from "./newfbdfhdf 1.png";
export { default as HTGSBGImage } from "./HowToGetStartedBackGroundImage.png";
export { default as AnimalImage } from "./FF With Shadow.png";
export { default as RegistrationGuideBGImage } from "./Educare kids_New.jpg";
export { default as bronze } from "./Bronze.png";
export { default as sliver } from "./Sliver.png";
export { default as gold } from "./Gold.png";
export { default as TeamProfileImage } from "./team-bg.png";
export { default as TeamProfileImage1 } from "./iBESTTeam.jpg";
export { default as DCDDPageBackGroundImage } from "./bgimage1.png";
export { default as DCDDPageWideBackGroundImage } from "./DCDDWideGB.png";
export { default as ThreeCharacterImage } from "./ThreeCharacter.png";
export { default as FamilyWithPhoneImage } from "./FamilyWithPhone.png";
export { default as CareerOpportunityImage } from "./Career.png";
export { default as Blog1 } from "./Blog1.png";
export { default as Blog2 } from "./Blog2.png";
export { default as Blog3 } from "./Blog3.png";
export { default as Blog4 } from "./Blog4.png";
export { default as Blog5 } from "./Blog5.png";
export { default as Contact } from "./Contact.png";
export { default as HMK5Image } from "./HMK5.png";
export { default as HMBGImage } from "./HMBG.png";
export { default as HMBGMobileImage } from "./HMBGMobile.png";
export { default as EducarekidsBGImage } from "./EducarekidsBG.jpg";
export { default as GirlPointImage } from "./GirlPointingImage.png";
export { default as CloudeFrameImage } from "./CloudFrame.png";
export { default as ManHoldingABabyImage } from "./ManHolingABaby.png";
export { default as GiftLineImage } from "./GiftLineimage.png";
export { default as Founder } from "./founder.png";
export { default as CEO } from "./CEO.png";
export { default as PIC } from "./PIC.png";
export { default as LeadershipBG } from "./BG.jpg";
export { default as DCDDTextImage } from "./DCDDTextImage.png";
export { default as iBESTOroginalImage } from "./iBEST Originals BG copy.jpg";
export { default as BCSEImage } from "./Undergraduite BG copy.jpg";
export { default as iBestOrognalIcon } from "./iBEST Orginal_150 x 150_1.png";
export { default as BCSEIcon } from "./Undergraduate_150-x-150.png";
export { default as MonkeyAndDragonImage } from "./Chara1.png";
export { default as DoodleImage } from "./Doodle.png";
export { default as DoodleLessOpacityImage } from "./Doodle_OpicityLess.png";
export { default as K5Image } from "./K5.jpg";
export { default as K5PhoneImage } from "./K5Mobile.jpg";

export * from "./logo";
export * from "./social-media";
export * from "./educare-skill";
export * from "./frames";
export * from "./why-choose-us";
export * from "./silders";
export * from "./Box";
export * from "./Team_New";
